// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8Zmuw5SWb2E-d9q7uQh8XZN1y_9ODdYE',
    appId: '1:762698214203:web:fe9ae147f5f4641ba8651e',
    messagingSenderId: '762698214203',
    projectId: 'zapfen',
    authDomain: 'zapfen.firebaseapp.com',
    storageBucket: 'zapfen.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhuDp6KeJQ3g7f0nIHQMlq0_krjFzxx-I',
    appId: '1:762698214203:android:8af6de5520615ec9a8651e',
    messagingSenderId: '762698214203',
    projectId: 'zapfen',
    storageBucket: 'zapfen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXfK31w0jxY5MaMeIPBF9GQ_8rekepHMg',
    appId: '1:762698214203:ios:16f0f4028e621624a8651e',
    messagingSenderId: '762698214203',
    projectId: 'zapfen',
    storageBucket: 'zapfen.firebasestorage.app',
    iosBundleId: 'de.maxengl.zapfen.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXfK31w0jxY5MaMeIPBF9GQ_8rekepHMg',
    appId: '1:762698214203:ios:d036fd799df29e7ca8651e',
    messagingSenderId: '762698214203',
    projectId: 'zapfen',
    storageBucket: 'zapfen.firebasestorage.app',
    iosBundleId: 'beerreal.max-engl.de.beerreal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8Zmuw5SWb2E-d9q7uQh8XZN1y_9ODdYE',
    appId: '1:762698214203:web:f0f57fe2dd3fb45ba8651e',
    messagingSenderId: '762698214203',
    projectId: 'zapfen',
    authDomain: 'zapfen.firebaseapp.com',
    storageBucket: 'zapfen.firebasestorage.app',
  );
}
