services:
  backend:
    image: maxengl/zapfenbackend:latest
    container_name: zapfen_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://admin:password123@mongodb:27017/social_app?authSource=admin
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    container_name: social_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: social_app
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
