services:
  backend:
    build: ./backend
    container_name: zapfen_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      MONGO_URI: mongodb://admin:password123@social_mongodb:27017/social_app?authSource=admin
    depends_on:
      - mongodb

  websiteserver:
    image: node:22-alpine
    container_name: pint_websiteserver
    restart: unless-stopped
    working_dir: /app/websiteserver
    command: [ "node", "server.js" ]
    ports:
      - "4000:4000"
    volumes:
      - .:/app:ro

  mongodb:
    image: mongo:7
    container_name: social_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: social_app
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
